[build]
  command = "NODE_ENV=development npm install && npm run typecheck && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

[functions]
  external_node_modules = ["@netlify/functions"]

# Disable secrets scanning completely
[security]
  SECRETS_SCAN_ENABLED = false
