[build]
  command = "NODE_ENV=development npm install && npm run typecheck && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[secrets]
  SECRETS_SCAN_ENABLED = true
  SECRETS_SCAN_OMIT_PATHS = [
    "**/dist/**",
    "**/dist/assets/**",
    "**/dist/assets/*.js",
    "**/dist/assets/index-*.js"
  ]
