[build]
  command = "export PATH=\"$PATH:$(pwd)/node_modules/.bin\" && NODE_ENV=production npm ci && NODE_ENV=production npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Opt out of asset optimization since we're handling it in Vite
[build.processing]
  skip_processing = true

# Configure secrets scanning
[build.secrets]
  SECRETS_SCAN_ENABLED = true
  SECRETS_SCAN_PATHS = ["!dist/**"]
